// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Request
	Response
	Router
	Send
	Notify
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_MESSAGE_SEND   Operation = 0
	Operation_MESSAGE_SYNC   Operation = 1
	Operation_MESSAGE_NOTIFY Operation = 2
	Operation_MESSAGE_ACK    Operation = 3
	Operation_MESSAGE_READ   Operation = 4
	Operation_MESSAGE_ENCRY  Operation = 5
	Operation_MESSAGE_PULL   Operation = 6
)

var Operation_name = map[int32]string{
	0: "MESSAGE_SEND",
	1: "MESSAGE_SYNC",
	2: "MESSAGE_NOTIFY",
	3: "MESSAGE_ACK",
	4: "MESSAGE_READ",
	5: "MESSAGE_ENCRY",
	6: "MESSAGE_PULL",
}
var Operation_value = map[string]int32{
	"MESSAGE_SEND":   0,
	"MESSAGE_SYNC":   1,
	"MESSAGE_NOTIFY": 2,
	"MESSAGE_ACK":    3,
	"MESSAGE_READ":   4,
	"MESSAGE_ENCRY":  5,
	"MESSAGE_PULL":   6,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	SourceId  uint64    `protobuf:"varint,1,opt,name=sourceId" json:"sourceId,omitempty"`
	TargetId  uint64    `protobuf:"varint,2,opt,name=targetId" json:"targetId,omitempty"`
	Seq       uint64    `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	MsgId     uint64    `protobuf:"varint,4,opt,name=msgId" json:"msgId,omitempty"`
	Operation Operation `protobuf:"varint,5,opt,name=operation,enum=protocol.Operation" json:"operation,omitempty"`
	Timestamp uint64    `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Router    *Router   `protobuf:"bytes,7,opt,name=router" json:"router,omitempty"`
	Body      []byte    `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetSourceId() uint64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Request) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Request) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Request) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Request) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_MESSAGE_SEND
}

func (m *Request) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Request) GetRouter() *Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	SourceId  uint64    `protobuf:"varint,1,opt,name=sourceId" json:"sourceId,omitempty"`
	TargetId  uint64    `protobuf:"varint,2,opt,name=targetId" json:"targetId,omitempty"`
	MsgId     uint64    `protobuf:"varint,3,opt,name=msgId" json:"msgId,omitempty"`
	Seq       uint64    `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	Operation Operation `protobuf:"varint,5,opt,name=operation,enum=protocol.Operation" json:"operation,omitempty"`
	Timestamp uint64    `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Router    *Router   `protobuf:"bytes,7,opt,name=router" json:"router,omitempty"`
	Body      []byte    `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetSourceId() uint64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Response) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Response) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Response) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Response) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_MESSAGE_SEND
}

func (m *Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Response) GetRouter() *Router {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// Router 是标明这条消息由哪个客户端发出
type Router struct {
	MachineId uint64 `protobuf:"varint,1,opt,name=machineId" json:"machineId,omitempty"`
	ProcessId uint64 `protobuf:"varint,2,opt,name=processId" json:"processId,omitempty"`
	CientId   uint64 `protobuf:"varint,3,opt,name=cientId" json:"cientId,omitempty"`
}

func (m *Router) Reset()                    { *m = Router{} }
func (m *Router) String() string            { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()               {}
func (*Router) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Router) GetMachineId() uint64 {
	if m != nil {
		return m.MachineId
	}
	return 0
}

func (m *Router) GetProcessId() uint64 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *Router) GetCientId() uint64 {
	if m != nil {
		return m.CientId
	}
	return 0
}

// only support text at first
type Send struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Send) Reset()                    { *m = Send{} }
func (m *Send) String() string            { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()               {}
func (*Send) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Send) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Notify struct {
	LastMsgId uint64 `protobuf:"varint,1,opt,name=lastMsgId" json:"lastMsgId,omitempty"`
}

func (m *Notify) Reset()                    { *m = Notify{} }
func (m *Notify) String() string            { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()               {}
func (*Notify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Notify) GetLastMsgId() uint64 {
	if m != nil {
		return m.LastMsgId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Response)(nil), "protocol.Response")
	proto.RegisterType((*Router)(nil), "protocol.Router")
	proto.RegisterType((*Send)(nil), "protocol.Send")
	proto.RegisterType((*Notify)(nil), "protocol.Notify")
	proto.RegisterEnum("protocol.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x90, 0xc1, 0xce, 0x93, 0x40,
	0x14, 0x85, 0x9d, 0x1f, 0x4a, 0xe1, 0xb6, 0xd6, 0x71, 0x74, 0x31, 0x69, 0x5c, 0x10, 0x16, 0x86,
	0xb8, 0x68, 0x62, 0x7d, 0x82, 0xa6, 0x45, 0x43, 0x6c, 0xa9, 0x19, 0x74, 0xd1, 0x8d, 0x86, 0xc2,
	0x58, 0x49, 0x0a, 0x43, 0x99, 0x69, 0x62, 0x9f, 0xc1, 0x17, 0xd6, 0x9d, 0x61, 0x5a, 0xa0, 0x6e,
	0x5d, 0xfd, 0xbb, 0x7b, 0xbe, 0x33, 0xdc, 0xcb, 0x39, 0x30, 0xa9, 0x6a, 0xa1, 0x44, 0x2a, 0x8e,
	0x33, 0x3d, 0x10, 0xbb, 0xd5, 0xde, 0x6f, 0x04, 0x43, 0xc6, 0x4f, 0x67, 0x2e, 0x15, 0x99, 0x82,
	0x2d, 0xc5, 0xb9, 0x4e, 0x79, 0x98, 0x51, 0xe4, 0x22, 0xdf, 0x64, 0x9d, 0x6e, 0x3c, 0x95, 0xd4,
	0x07, 0xae, 0xc2, 0x8c, 0x3e, 0x5c, 0xbd, 0x56, 0x13, 0x0c, 0x86, 0xe4, 0x27, 0x6a, 0x68, 0xdc,
	0x8c, 0xe4, 0x25, 0x0c, 0x0a, 0x79, 0x08, 0x33, 0x6a, 0x6a, 0x76, 0x15, 0xe4, 0x2d, 0x38, 0xa2,
	0xe2, 0x75, 0xa2, 0x72, 0x51, 0xd2, 0x81, 0x8b, 0xfc, 0xc9, 0xfc, 0xc5, 0xac, 0xfb, 0xb3, 0x6d,
	0x6b, 0xb1, 0xfe, 0x15, 0x79, 0x05, 0x8e, 0xca, 0x0b, 0x2e, 0x55, 0x52, 0x54, 0xd4, 0xd2, 0xcb,
	0x7a, 0x40, 0x7c, 0xb0, 0x6a, 0x71, 0x56, 0xbc, 0xa6, 0x43, 0x17, 0xf9, 0xa3, 0x39, 0xee, 0xb7,
	0x31, 0xcd, 0xd9, 0xcd, 0x27, 0x04, 0xcc, 0xbd, 0xc8, 0x2e, 0xd4, 0x76, 0x91, 0x3f, 0x66, 0x7a,
	0xf6, 0xfe, 0x20, 0xb0, 0x19, 0x97, 0x95, 0x28, 0x25, 0xff, 0xef, 0xec, 0x5d, 0x52, 0xe3, 0x3e,
	0xe9, 0xad, 0x11, 0xb3, 0x6f, 0xe4, 0x91, 0x65, 0xff, 0x0a, 0xd6, 0xf5, 0x55, 0x73, 0xa5, 0x48,
	0xd2, 0x1f, 0x79, 0xd9, 0x27, 0xef, 0x41, 0xe3, 0x56, 0xb5, 0x48, 0xb9, 0x94, 0x5d, 0xf6, 0x1e,
	0x10, 0x0a, 0xc3, 0x34, 0xe7, 0xa5, 0xea, 0xe2, 0xb7, 0xd2, 0x9b, 0x82, 0x19, 0xf3, 0x32, 0x6b,
	0x6e, 0x2b, 0xfe, 0x53, 0xe9, 0xc5, 0x0e, 0xd3, 0xb3, 0xf7, 0x1a, 0xac, 0x48, 0xa8, 0xfc, 0xfb,
	0xa5, 0xd9, 0x7e, 0x4c, 0xa4, 0xda, 0xe8, 0x02, 0x6f, 0xb7, 0x3b, 0xf0, 0xe6, 0x17, 0x02, 0xa7,
	0x2b, 0x86, 0x60, 0x18, 0x6f, 0x82, 0x38, 0x5e, 0x7c, 0x08, 0xbe, 0xc5, 0x41, 0xb4, 0xc2, 0x4f,
	0xfe, 0x21, 0xbb, 0x68, 0x89, 0x11, 0x21, 0x30, 0x69, 0x49, 0xb4, 0xfd, 0x1c, 0xbe, 0xdf, 0xe1,
	0x07, 0xf2, 0x0c, 0x46, 0x2d, 0x5b, 0x2c, 0x3f, 0x62, 0xe3, 0xfe, 0x33, 0x16, 0x2c, 0x56, 0xd8,
	0x24, 0xcf, 0xe1, 0x69, 0x4b, 0x82, 0x68, 0xc9, 0x76, 0x78, 0x70, 0xff, 0xe8, 0xd3, 0x97, 0xf5,
	0x1a, 0x5b, 0x7b, 0x4b, 0xd7, 0xfb, 0xee, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xf3, 0xa8,
	0x92, 0x4b, 0x03, 0x00, 0x00,
}
