// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Request
	Response
	Send
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_MESSAGE_SEND   Operation = 0
	Operation_MESSAGE_SYNC   Operation = 1
	Operation_MESSAGE_NOTIFY Operation = 2
	Operation_MESSAGE_ACK    Operation = 3
	Operation_MESSAGE_READ   Operation = 4
	Operation_MESSAGE_ENCRY  Operation = 5
)

var Operation_name = map[int32]string{
	0: "MESSAGE_SEND",
	1: "MESSAGE_SYNC",
	2: "MESSAGE_NOTIFY",
	3: "MESSAGE_ACK",
	4: "MESSAGE_READ",
	5: "MESSAGE_ENCRY",
}
var Operation_value = map[string]int32{
	"MESSAGE_SEND":   0,
	"MESSAGE_SYNC":   1,
	"MESSAGE_NOTIFY": 2,
	"MESSAGE_ACK":    3,
	"MESSAGE_READ":   4,
	"MESSAGE_ENCRY":  5,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	SourceId  uint64    `protobuf:"varint,1,opt,name=sourceId" json:"sourceId,omitempty"`
	TargetId  uint64    `protobuf:"varint,2,opt,name=targetId" json:"targetId,omitempty"`
	Operation Operation `protobuf:"varint,3,opt,name=operation,enum=protocol.Operation" json:"operation,omitempty"`
	MsgId     uint64    `protobuf:"varint,4,opt,name=msgId" json:"msgId,omitempty"`
	Timestamp uint64    `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Body      []byte    `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetSourceId() uint64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Request) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Request) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_MESSAGE_SEND
}

func (m *Request) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Request) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	MsgId     uint64    `protobuf:"varint,1,opt,name=msgId" json:"msgId,omitempty"`
	Timestamp uint64    `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Operation Operation `protobuf:"varint,3,opt,name=operation,enum=protocol.Operation" json:"operation,omitempty"`
	Body      []byte    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Response) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Response) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_MESSAGE_SEND
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// only support text at first
type Send struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Send) Reset()                    { *m = Send{} }
func (m *Send) String() string            { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()               {}
func (*Send) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Send) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Response)(nil), "protocol.Response")
	proto.RegisterType((*Send)(nil), "protocol.Send")
	proto.RegisterEnum("protocol.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0x4f, 0x4f, 0xf2, 0x30,
	0x1c, 0xc7, 0x9f, 0x42, 0xe1, 0x61, 0x3f, 0x11, 0xeb, 0x4f, 0x0f, 0x0d, 0xf1, 0x40, 0x38, 0x11,
	0x0f, 0x24, 0xea, 0x2b, 0x20, 0x63, 0x9a, 0xc5, 0x38, 0x92, 0xce, 0xcb, 0x4e, 0x66, 0xb0, 0x86,
	0x90, 0xb8, 0x75, 0xae, 0x25, 0x91, 0x17, 0xe0, 0xbb, 0xf2, 0xc5, 0x19, 0x4a, 0xba, 0xa1, 0x89,
	0x17, 0x6f, 0xdf, 0x3f, 0xed, 0xa7, 0xdf, 0xc2, 0xa0, 0xac, 0x94, 0x51, 0x2b, 0xf5, 0x3a, 0xb5,
	0x02, 0x7b, 0xce, 0x8f, 0x3f, 0x09, 0xfc, 0x17, 0xf2, 0x6d, 0x2b, 0xb5, 0xc1, 0x21, 0xf4, 0xb4,
	0xda, 0x56, 0x2b, 0x19, 0x66, 0x9c, 0x8c, 0xc8, 0x84, 0x8a, 0xda, 0xef, 0x3b, 0x93, 0x56, 0x6b,
	0x69, 0xc2, 0x8c, 0xb7, 0x0e, 0x9d, 0xf3, 0x78, 0x03, 0x9e, 0x2a, 0x65, 0x95, 0x9a, 0x8d, 0x2a,
	0x78, 0x7b, 0x44, 0x26, 0x83, 0xdb, 0x8b, 0x69, 0xfd, 0xe2, 0xc2, 0x55, 0xa2, 0x39, 0x85, 0x97,
	0xd0, 0xc9, 0xf5, 0x3a, 0xcc, 0x38, 0xb5, 0xac, 0x83, 0xc1, 0x2b, 0xf0, 0xcc, 0x26, 0x97, 0xda,
	0xa4, 0x79, 0xc9, 0x3b, 0xb6, 0x69, 0x02, 0x44, 0xa0, 0x4b, 0x95, 0xed, 0x78, 0x77, 0x44, 0x26,
	0x7d, 0x61, 0xf5, 0xf8, 0x83, 0x40, 0x4f, 0x48, 0x5d, 0xaa, 0x42, 0xcb, 0x06, 0x4a, 0x7e, 0x85,
	0xb6, 0x7e, 0x42, 0xff, 0xb0, 0xdd, 0xed, 0xa0, 0x47, 0x3b, 0x86, 0x40, 0x63, 0x59, 0x64, 0xfb,
	0xce, 0xc8, 0x77, 0x63, 0x17, 0x78, 0xc2, 0xea, 0xeb, 0x1d, 0x78, 0x35, 0x07, 0x19, 0xf4, 0x9f,
	0x82, 0x38, 0x9e, 0x3d, 0x04, 0x2f, 0x71, 0x10, 0xcd, 0xd9, 0xbf, 0x6f, 0x49, 0x12, 0xf9, 0x8c,
	0x20, 0xc2, 0xc0, 0x25, 0xd1, 0xe2, 0x39, 0xbc, 0x4f, 0x58, 0x0b, 0xcf, 0xe0, 0xc4, 0x65, 0x33,
	0xff, 0x91, 0xb5, 0x8f, 0xaf, 0x89, 0x60, 0x36, 0x67, 0x14, 0xcf, 0xe1, 0xd4, 0x25, 0x41, 0xe4,
	0x8b, 0x84, 0x75, 0x96, 0x5d, 0xfb, 0x93, 0xbb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x54,
	0x06, 0xf4, 0x00, 0x02, 0x00, 0x00,
}
